auto INTERP_NAME_adouble = [&GDSGE_CPP_ASG,&GDSGE_ASG_CELL,&GDSGE_ASG_RATIO,&GDSGE_ASG_SLOPE,&GDSGE_INTERP_RSLT_adouble,&GDSGE_INTERP_GRAD](int shockIdx, ADOUBLE_VAR_NAME)
{
  adouble xSite[] = {VAR_NAME};
  GDSGE_CPP_ASG.eval_adouble(shockIdx-1, INTERP_IDX, xSite, GDSGE_ASG_CELL, GDSGE_ASG_RATIO, GDSGE_ASG_SLOPE,
	  GDSGE_INTERP_RSLT_adouble, GDSGE_INTERP_GRAD);
  return GDSGE_INTERP_RSLT_adouble[0];
};

auto INTERP_NAME_double = [&GDSGE_CPP_ASG,&GDSGE_ASG_CELL,&GDSGE_ASG_RATIO,&GDSGE_ASG_SLOPE,&GDSGE_INTERP_RSLT_double](int shockIdx, DOUBLE_VAR_NAME)
{
  double xSite[] = {VAR_NAME};
  GDSGE_CPP_ASG.eval_double(shockIdx-1, INTERP_IDX, xSite, GDSGE_ASG_CELL, GDSGE_ASG_RATIO, GDSGE_ASG_SLOPE,
	  GDSGE_INTERP_RSLT_double);
  return GDSGE_INTERP_RSLT_double[0];
};