GET_STRUCT(GDSGE_PP_INTERP_NAME);
MatlabPp<VAR_NUM,INTERP_ORDER> GDSGE_CPP_INTERP_NAME(GDSGE_PP_INTERP_NAME);
auto INTERP_NAME_adouble = [&GDSGE_CPP_INTERP_NAME](int shockIdx, ADOUBLE_VAR_NAME)
{
  adouble xSite[] = {VAR_NAME};
  int GDSGE_INTERP_CELL[GDSGE_INTERP_XDIM];
  return GDSGE_CPP_INTERP_NAME.eval_INTERP_ORDER(xSite, GDSGE_INTERP_CELL, shockIdx-1);
};

auto INTERP_NAME_double = [&GDSGE_CPP_INTERP_NAME](int shockIdx, DOUBLE_VAR_NAME)
{
  double xSite[] = {VAR_NAME};
  int GDSGE_INTERP_CELL[GDSGE_INTERP_XDIM];
  return GDSGE_CPP_INTERP_NAME.eval_INTERP_ORDER(xSite, GDSGE_INTERP_CELL, shockIdx-1);
};
