
GDSGE_DATA_MODEL_ID(:) = [repmat([shock_num;PARAMS_SEMI_COLON;shock_trans(:);SHOCK_GRID_SEMI_COLON],1,GDSGE_NPROB_MODEL_ID);GDSGE_TENSOR_shockIdx_MODEL_ID(:)';STATE_SEMI_COLON TENSOR_SEMI_COLON];

MEX_TASK_NAME = MEX_TASK_INF_HORIZON;
SOLVE_PROBLEM_CODE

POLICY_ASSIGN_CODE

AUX_ASSIGN_CODE