GDSGE_INTERP_ORDER_MODEL_ID = INTERP_ORDER*ones(1,length(GDSGE_SIZE_STATE_MODEL_ID));
if INTERP_ORDER==4
GDSGE_EXTRAP_ORDER_MODEL_ID = EXTRAP_ORDER*ones(1,length(GDSGE_SIZE_STATE_MODEL_ID));
else
GDSGE_EXTRAP_ORDER_MODEL_ID = [];
end

CONSTRUCT_INTERP_CODE

% Construct the vectorized spline
if ~GDSGE_USE_OLD_VEC
    GDSGE_SPLINE_VEC = convert_to_interp_eval_array({GDSGE_INTERP_ALL});
end
