% Construct output variables
outputVarStack = cat(1,OUTPUT_VAR_RESHAPE_COMMA);

% Permute variables from order (shock, var, states) to order (var,
% shock, states)
if shock_num>1
    outputVarStack = reshape(outputVarStack, [],shock_num,GDSGE_SIZE_STATE{:});
    output_interp=struct('form','MKL','breaks',{{1:shock_num,STATE_COMMA}},...
        'Values',outputVarStack,...
        'coefs',[],'order',[2 OutputInterpOrder*ones(1,length({STATE_COMMA}))],'Method',[],...
        'ExtrapolationOrder',[],'thread',NumThreads, ...
        'orient','curvefit');
else
    outputVarStack = reshape(outputVarStack, [],GDSGE_SIZE_STATE{:});
    output_interp=struct('form','MKL','breaks',{{STATE_COMMA}},...
        'Values',outputVarStack,...
        'coefs',[],'order',[OutputInterpOrder*ones(1,length({STATE_COMMA}))],'Method',[],...
        'ExtrapolationOrder',[],'thread',NumThreads, ...
        'orient','curvefit');
end
IterRslt.output_interp=myppual(output_interp);

OUTPUT_INDEX_ASSIGN_CODE
IterRslt.output_var_index = output_var_index;