function code = defaultSetupCode()
% DEFAULTSETUPCODE  Parser-owned default flag values — the IR-relevant subset of
%   the old default_mod.nmod + params_template.m. Prepended to a model's setup
%   script before eval, so options resolve and any gmod assignment overrides.
code = strjoin({ ...
    'INTERP_ORDER = 4;', ...
    'EXTRAP_ORDER = 2;', ...
    'USE_SPLINE = 1;', ...
    'USE_ASG = 0;', ...
    'USE_PCHIP = 0;', ...
    'SIMU_INTERP = 0;', ...
    'SIMU_RESOLVE = 1;', ...
    'AsgMinLevel = 4;', ...
    'AsgMaxLevel = 10;', ...
    'AsgThreshold = 1e-2;', ...
    'AsgOutputMaxLevel = 10;', ...
    'AsgOutputThreshold = 1e-2;', ...
    'TolEq = 1e-6;', ...
    'PrintFreq = 10;', ...
    'ResolvePrintFreq = 100;', ...
    'SaveFreq = 10;', ...
    'SimuPrintFreq = 1000;', ...
    'SimuSaveFreq = Inf;', ...
    'NumThreads = 0;', ...   % 0 = dynamic sentinel: codegen emits feature('numcores')
    'shock_num = 1;', ...
    'shock_trans = 1;' ...
    }, sprintf('\n'));
end
