function s = schema()
% SCHEMA  The single source of truth for the GDSGE IR.
%   Returns a descriptor struct with fields:
%     .irVersion  semver string
%     .root       a 'struct' field-spec whose .fields are the top-level sections
%     .nodes      registry of AST node specs, keyed by node kind
%     .stmts      registry of model-statement specs, keyed by statement type
%   Field kinds: scalar matrix text enum ref list map tagged taggedList struct.

s.irVersion = '2.0.0';

% ---- reusable item specs -------------------------------------------------
varItem = fStruct(structOf('name', fText(), 'length', fScalar(), 'slot', fMatrix()));

% var_tensor item: a name + its opaque-MATLAB-text assignment RHS (broadcast
% over the state×shock grid; feeds inbound bounds + initial interp values).
tensorItem = fStruct(structOf('name', fText(), 'expr', fText()));

% setup section: a declaration-region coding block (kind + verbatim body text).
% Bodies concatenated in list order reproduce the old single ir.setup string.
setupSection = fStruct(structOf('kind', fText(), 'body', fText()));

boundItem = fStruct(structOf( ...
    'name', fRef('policyAux'), ...
    'lower', fText(), ...
    'upper', fText(), ...
    'adaptiveFactor', opt(fScalar())));

initBoundItem = fStruct(structOf( ...
    'name', fText(), ...
    'lower', fText(), ...
    'upper', fText(), ...
    'adaptiveFactor', opt(fScalar())));

interpItem = fStruct(structOf( ...
    'name', fText(), ...
    'args', fList(fRef('states')), ...
    'initialExpr', fText(), ...
    'updateExpr', fText()));

% Phase 9b: equations are a tagged list (plain | conditional) over the eqkinds
% registry. plainEq is the pre-9b eqItem + a 'kind' tag; conditional carries
% ordered cases, each a guard (cond; '' = else) and its own plain equations.
fEqList = struct('kind','taggedList','required',true,'registry','eqkinds','tag','kind');
caseItem = fStruct(structOf('cond', fText(), 'equations', fEqList));
regionItem = fStruct(structOf( ...
    'condition',  fText(), ...
    'statements', fStmtList(), ...
    'equations',  fEqList));

initItem  = fStruct(structOf('var', fText(), 'value', fText()));
transItem = fStruct(structOf('state', fRef('states'), 'expr', fText(), 'primed', fScalar()));
paramItem = fStruct(structOf('name', fText(), 'value', fMatrix()));

% ---- top-level sections --------------------------------------------------
options = fStruct(structOf( ...
    'interpMethod', fEnum({'spline','asg','pchip'}), ...
    'jacobianBackend', opt(fEnum({'autodiff','sympy'})), ...
    'interpOrder',  opt(fScalar()), ...
    'extrapOrder',  opt(fScalar()), ...
    'asgMaxLevel',  opt(fScalar()), ...
    'asgThreshold', opt(fScalar()), ...
    'asgMinLevel',        opt(fScalar()), ...
    'asgOutputMaxLevel',  opt(fScalar()), ...
    'asgOutputThreshold', opt(fScalar()), ...
    'tolEq',        opt(fScalar()), ...
    'numThreads',   opt(fScalar()), ...
    'simuResolve',  opt(fScalar()), ...
    'simuInterp',   opt(fScalar()), ...
    'printFreq',    opt(fScalar()), ...
    'resolvePrintFreq', opt(fScalar()), ...
    'saveFreq',     opt(fScalar()), ...
    'simuPrintFreq',opt(fScalar()), ...
    'simuSaveFreq', opt(fScalar())));

shocks = fStruct(structOf( ...
    'names', fList(fText()), ...
    'count', fScalar(), ...
    'values', fMap(fMatrix()), ...
    'transitions', fMap(fMatrix())));

states = fStruct(structOf( ...
    'names', fList(fText()), ...
    'grids', fMap(fText())));

variables = fStruct(structOf( ...
    'policy', fList(varItem), ...
    'aux',    fList(varItem), ...
    'interp', fList(fRef('interpNames')), ...
    'tensor', fList(tensorItem), ...
    'output', fList(fRef('policyAux')), ...
    'others', fList(fText())));

model = fStruct(structOf('regions', fList(regionItem)));

modelInit = fStruct(structOf( ...
    'variables', fStruct(structOf('policyInit', fList(varItem), 'auxInit', fList(varItem))), ...
    'bounds',    fList(initBoundItem), ...
    'statements', fStmtList(), ...
    'equations',  fEqList));

simulate = fStruct(structOf( ...
    'numPeriods', fScalar(), ...
    'numSamples', fScalar(), ...
    'initial',    fList(initItem), ...
    'varSimu',    fList(fRef('policyAux')), ...
    'transitions', fList(transItem)));

hooks = fStruct(structOf( ...
    'preModel',    opt(fText()), ...
    'preIter',     opt(fText()), ...
    'postIter',    opt(fText()), ...
    'preJacCode',  opt(fText()), ...
    'postJacCode', opt(fText()), ...
    'cxx',         opt(fText()), ...
    'cxxIncludes', opt(fList(fText()))));

s.root = fStruct(structOf( ...
    'irVersion', fText(), ...
    'modelName', fText(), ...
    'params',    fList(paramItem), ...
    'setup',     opt(fList(setupSection)), ...
    'setupNames', opt(fList(fText())), ...
    'options',   options, ...
    'shocks',    shocks, ...
    'states',    states, ...
    'variables', variables, ...
    'bounds',    fList(boundItem), ...
    'interp',    fList(interpItem), ...
    'model',     model, ...
    'modelInit', opt(modelInit), ...
    'simulate',  simulate, ...
    'hooks',     hooks));

% NOTE: the node-kind set here is mirrored by hand in +node/ (one constructor
%       file per kind, plus children.m's switch). Keep them in sync.
% ---- AST node registry: a name->fStruct map. NOT wrapped in fStruct itself --
%      (callers look entries up by tag; the generic struct-walker never
%       recurses into this map).
s.nodes = structOf( ...
    'num',    fStruct(structOf('kind', fEnum({'num'}),    'value', fScalar())), ...
    'name',   fStruct(structOf('kind', fEnum({'name'}),   'id',    fText())), ...
    'primed', fStruct(structOf('kind', fEnum({'primed'}), 'id',    fText())), ...
    'unop',   fStruct(structOf('kind', fEnum({'unop'}),   'op', fText(), 'arg', fNode())), ...
    'binop',  fStruct(structOf('kind', fEnum({'binop'}),  'op', fText(), 'lhs', fNode(), 'rhs', fNode())), ...
    'call',   fStruct(structOf('kind', fEnum({'call'}),   'fn', fText(), 'args', fNodeList())), ...
    'index',  fStruct(structOf('kind', fEnum({'index'}),  'base', fNode(), 'args', fNodeList())));

% ---- model statement registry --------------------------------------------
s.stmts = structOf( ...
    'assign', fStruct(structOf( ...
        'type', fEnum({'assign'}), 'target', fText(), 'primed', fScalar(), 'expr', fNode())), ...
    'interpCall', fStruct(structOf( ...
        'type', fEnum({'interpCall'}), 'targets', fList(fText()), 'primed', fScalar(), ...
        'args', fNodeList(), 'interpRef', fText())), ...
    'reduction', fStruct(structOf( ...
        'type', fEnum({'reduction'}), 'kind', fEnum({'EXPECT','MIN','MAX','PROD'}), ...
        'target', fText(), 'body', fNode(), 'transRef', fRef('transitions'))));

% ---- equation-kind registry (Phase 9b) -----------------------------------
%      plain: a single residual (the pre-9b equation). conditional: a runtime
%      branch on a shock guard selecting which plain equation(s) fill the slot.
s.eqkinds = structOf( ...
    'plain', fStruct(structOf('kind', fEnum({'plain'}), 'expr', fNode(), 'primed', fScalar())), ...
    'conditional', fStruct(structOf('kind', fEnum({'conditional'}), 'cases', fList(caseItem))));
end

% ===== field-spec constructors (local) ====================================
function s = fScalar(),  s.kind = 'scalar';  s.required = true; end
function s = fMatrix(),  s.kind = 'matrix';  s.required = true; end
function s = fText(),    s.kind = 'text';    s.required = true; end
function s = fEnum(vals),s.kind = 'enum';    s.required = true; s.values = vals; end
function s = fRef(pool), s.kind = 'ref';     s.required = true; s.pool = pool; end
function s = fNode(),    s.kind = 'tagged';     s.required = true; s.registry = 'nodes'; s.tag = 'kind'; end
function s = fNodeList(),s.kind = 'taggedList'; s.required = true; s.registry = 'nodes'; s.tag = 'kind'; end
function s = fStmtList(),s.kind = 'taggedList'; s.required = true; s.registry = 'stmts'; s.tag = 'type'; end
function s = fList(item),s.kind = 'list';    s.required = true; s.item = item; end
function s = fMap(val),  s.kind = 'map';     s.required = true; s.value = val; end
function s = fStruct(flds), s.kind = 'struct'; s.required = true; s.fields = flds; end
function s = opt(spec),  spec.required = false; s = spec; end

% structOf('a',specA,'b',specB,...) builds a struct mapping names to specs,
% preserving insertion order (used for deterministic field order in JSON/doc).
function st = structOf(varargin)
st = struct();
for i = 1:2:numel(varargin)
    st.(varargin{i}) = varargin{i+1};
end
end
