% Generated by gdsge.codegen.generateCxx — License: Apache 2.0, http://github.com/gdsge/gdsge/LICENSE
function compile_MODEL_NAME(GDSGE_OPTIONS)
clear mex;
current_folder = fileparts(mfilename('fullpath'));
include_folder = 'INCLUDE_FOLDER';

DEBUG = nargin>=1 && isfield(GDSGE_OPTIONS,'DEBUG') && GDSGE_OPTIONS.DEBUG;

flag0 = '';
flag1 = [' -DMAXDIM=GDSGE_MAXDIM -DGDSGE_SOLVE_DIM=GDSGE_SOLVE_DIM -DINTERP_ORDER=GDSGE_INTERP_ORDER -DEIGEN_DONT_PARALLELIZE ' 'EXTRA_DEF'];
flag2 = '';
flag3 = '';
link_to_lib = '';   % default for all platforms; the ispc branch may override it. Defined here so the simulate-MEX compile resolves it on Linux/macOS too.

cppFileName = fullfile(current_folder,'mex_MODEL_NAME.cpp');

if ispc
    compiler_name = mex.getCompilerConfigurations('C++').Name;
    if contains(compiler_name, 'MinGW64')
        compiler_name = 'MinGW64';
    elseif contains(compiler_name, 'Microsoft Visual C++')
        compiler_name = 'MSVC';
    else
        compiler_name = 'Intel';
    end
elseif isunix
    compiler_name = 'g++';
end

if ispc
    mexCommand = 'mex';
    switch compiler_name
        case 'MinGW64'
            flag2 = ' CXXOPTIMFLAGS="-O -DNDEBUG" CFLAGS="$CFLAGS -w -fopenmp -fpermissive -DADEPT_THREAD_LOCAL=__thread"';
            flag3 = ' LDFLAGS="$LDFLAGS -w -fopenmp"';
        case 'MSVC'
            flag2 = ' OPTIMFLAGS="/O2 /DNDEBUG" COMPFLAGS="$COMPFLAGS /wd4267 /wd4068 /wd4091 /diagnostics:caret /openmp /Z7"';
            flag3 = ' LINKOPTIMFLAGS="/DEBUG:FULL"';
        otherwise
            flag2 = ' OPTIMFLAGS="/O2 /DNDEBUG" COMPFLAGS="$COMPFLAGS /wd4267 /wd4068 /wd4091 /Qansi-alias /openmp"';
    end
    if DEBUG
        flag2 = ' -v OPTIMFLAGS="/Og /Z7 /Zo /debug:full " COMPFLAGS="$COMPFLAGS "';
        flag3 = ' LINKOPTIMFLAGS="/DEBUG:FULL"';
    end
    switch compiler_name
        case 'MinGW64'
            link_to_lib = '';
        case 'MSVC'
            link_to_lib = '';
        otherwise
            error('compiler not supported');
    end
    compileString = [mexCommand ' ' flag0 flag1 flag2 flag3 sprintf(' "%s"',cppFileName) link_to_lib ' -outdir "' current_folder '"' ' -I"' include_folder '"'];
elseif isunix && ~ismac
    mexCommand = 'mex CXX=gcc';
    flag2 = ' CXXOPTIMFLAGS="-O -DNDEBUG" CFLAGS="$CFLAGS -w -fopenmp -fpermissive -fexceptions -DADEPT_THREAD_LOCAL=__thread"';
    flag3 = ' LDFLAGS="$LDFLAGS -w -fopenmp"';
    compileString = [mexCommand ' ' flag0 flag1 flag2 flag3 ' "' cppFileName '" -outdir "' current_folder '"' ' -I"' include_folder '"'];
elseif ismac
    mexCommand = 'mex';
    flag2 = ' CFLAGS="$CFLAGS -w -fopenmp -fpermissive -fexceptions -DADEPT_THREAD_LOCAL=__thread"';
    flag3 = ' LDFLAGS="$LDFLAGS -w -lomp"';
    compileString = [mexCommand ' ' flag0 flag1 flag2 flag3 ' "' cppFileName '" -outdir "' current_folder '"' ' -I"' include_folder '"'];
end
eval(compileString);

SIMU_MEX_COMPILE
end
