// Generated by gdsge.codegen.cxx.emitSimulateMex — do not edit.
// simulate_MODEL_NAME_mex(int32 numThreads, output_interp_pp, int32 nComp,
//                         shockMat, simuStruct, int32 [t0 t1], int32 num_periods,
//                         int32 EnforceSimuStateInbound, int32 SimuPrintFreq)
// Whole SIMU_INTERP period loop, in place. Stacked uniform-order interp:
// output row r at realized shock s is vector index (s-1)*nComp + r (0-based).
// The interpolation ORDER is read from the pp at runtime (output_interp is built
// with OutputInterpOrder, default 2), so the loop is dispatched on it.
#include "mex.h"
#include "interp_eval_double.h"
#include <omp.h>
#include "pin_omp_runtime.h"
#define MAXDIM 10

using gdsge_eval::PpEval;

template <int XDIM, int ORDER>
static void run(const mxArray* pp, const double* shockMat, mxArray* simu,
                int t0, int t1, int num_periods, int nComp,
                int enforceInbound, int printFreq, int num_samples)
{
    PpEval<XDIM, ORDER> ev(pp);
    double gmin[MAXDIM], gmax[MAXDIM];
    for (int d = 0; d < XDIM; ++d) { gmin[d] = ev.xGrid[d][0]; gmax[d] = ev.xGrid[d][ev.xPts[d]-1]; }

    // field pointers (written in place)
    STATE_FIELD_SETUP
    VARSIMU_FIELD_SETUP

    for (int t = t0; t <= t1; ++t)
    {
        const double* shockT  = shockMat + (size_t)(t-1)*num_samples;
        const double* shockT1 = shockMat + (size_t)(t)*num_samples;   // next period
        #pragma omp parallel for
        for (int i = 0; i < num_samples; ++i)
        {
            double xSite[MAXDIM], xLeft[MAXDIM];
            int cell[MAXDIM];
            for (int d = 0; d < XDIM; ++d) {
                double s = state[d][(size_t)(t-1)*num_samples + i];
                if (enforceInbound) { if (s < gmin[d]) s = gmin[d]; if (s > gmax[d]) s = gmax[d]; }
                state[d][(size_t)(t-1)*num_samples + i] = s;   // matches MATLAB clamp-write
                xSite[d] = s;
            }
            ev.search(xSite, cell, xLeft);
            int base = ((int)shockT[i]-1) * nComp;
            int nextShock = (int)shockT1[i];                   // 1-based
            RECORD_AND_TRANSITION_CODE
        }
        if (printFreq > 0 && (t % printFreq == 0)) {
            mexPrintf("Periods: %d\n", t);
            PRINT_FIELDS_CODE
            mexEvalString("drawnow;");
        }
    }
}

void mexFunction(int nlhs, mxArray* plhs[], int nrhs, const mxArray* prhs[])
{
    int numThreads = *((int*)mxGetData(prhs[0]));
    omp_set_num_threads(numThreads);
    const mxArray* pp = prhs[1];
    int nComp = *((int*)mxGetData(prhs[2]));
    const double* shockMat = mxGetPr(prhs[3]);   // num_samples x (num_periods+1)
    mxArray* simu = (mxArray*)prhs[4];
    const int* trange = (const int*)mxGetData(prhs[5]);
    int t0 = trange[0], t1 = trange[1];
    int num_periods = *((int*)mxGetData(prhs[6]));
    int enforceInbound = *((int*)mxGetData(prhs[7]));
    int printFreq = *((int*)mxGetData(prhs[8]));
    int num_samples = (int)mxGetM(prhs[3]);

    int order0 = *((int*)mxGetData(mxGetField(pp, 0, "order")));   // OutputInterpOrder
    if (order0 == 4)
        run<GDSGE_NSTATES, 4>(pp, shockMat, simu, t0, t1, num_periods, nComp, enforceInbound, printFreq, num_samples);
    else
        run<GDSGE_NSTATES, 2>(pp, shockMat, simu, t0, t1, num_periods, nComp, enforceInbound, printFreq, num_samples);
}
