function txt = emitIterAsg(ir)
% EMITITERASG  iter_<model>.m for interpMethod='asg'.
%   Old-template parity: iter_inf_horizon_asg_template.m with
%   asg_propose_grids_and_solve_template.m inlined (interp loop + output
%   construct) and iter_init_asg_template.m as the init segment. Differences
%   from the spline emitIter: no state-space tensors — each fixed-point
%   iteration rebuilds the interpolant by level-by-level adaptive refinement;
%   per-problem GDSGE_DATA rows are the proposed eval grids; the MEX
%   evaluates the PREVIOUS iteration's interpolant through GDSGE_ASG_HANDLE.
%   Deliberately not emitted (spec 7b §2 — no corpus driver exercises them):
%   the GDSGE_ASG_FIX_GRID branch, PRE_ITER/POST_ITER hooks. Progress goes
%   through gdsge.runtime.printIterProgress (7a precedent: console format is
%   a deliberate simplification; results are unaffected).
%   Naming: the output-construct loop uses GDSGE_ASG_INTERP_OUTPUT where the
%   old template reused GDSGE_ASG_INTERP_NEW (renamed to avoid aliasing the
%   iteration interpolant after the update step).
m           = ir.modelName;
bounds      = gdsge.codegen.mat.emitBounds(ir, 'asg');
pack        = gdsge.codegen.mat.emitDataPack(ir);
unpk        = gdsge.codegen.mat.emitSolUnpack(ir);
interpNames = ir.variables.interp;
stateList   = strjoin(ir.states.names, ',');
stateGridCell = ['{' stateList '}'];
interpSemi  = strjoin(interpNames, ';');
nAux = 0;
for i = 1:numel(ir.variables.aux); nAux = max(nAux, ir.variables.aux{i}.slot(2)); end
numPolicyTotal = sum(cellfun(@(p) p.length, ir.variables.policy));
outputs = ir.variables.output;
lenOf = struct();
for i = 1:numel(ir.variables.policy); lenOf.(ir.variables.policy{i}.name) = ir.variables.policy{i}.length; end
for i = 1:numel(ir.variables.aux);    lenOf.(ir.variables.aux{i}.name)    = ir.variables.aux{i}.length;    end
numOutputTotal = 0;
for i = 1:numel(outputs); numOutputTotal = numOutputTotal + lenOf.(outputs{i}); end
outputSemi = strjoin(outputs, ';');
main = struct('bounds', bounds, 'unpack', unpk.unpack, 'unpackAux', unpk.unpackAux, ...
    'maxDim', bounds.maxDim, 'nAux', max(nAux, 1));

w = gdsge.codegen.codeWriter();
w.add('%% Generated by gdsge.codegen.generateMatlab — do not edit.');
w.add('function [IterRslt,IterFlag] = iter_%s(GDSGE_OPTIONS)', m);
w.add('gdsge.runtime.ensurePath();');
w.blank();
w.addRaw(gdsge.codegen.mat.emitSetup(ir, 'iter'));
w.blank();
w.add('GDSGE_OPTIONS_VALID = %s;', gdsge.codegen.mat.optionsWhitelist(ir, {}));
w.add('if nargin < 1; GDSGE_OPTIONS = struct(); end');
w.add('gdsge.runtime.unpackOptions(GDSGE_OPTIONS, GDSGE_OPTIONS_VALID);');
w.blank();
w.add('assert(exist(''shock_num'',''var'')==1);');
for i = 1:numel(ir.shocks.names)
    w.add('assert(length(%s)==%d);', ir.shocks.names{i}, ir.shocks.count);
end
tn = fieldnames(ir.shocks.transitions);
for i = 1:numel(tn)
    w.add('assert(size(%s,1)==%d);', tn{i}, ir.shocks.count);
    w.add('assert(size(%s,2)==%d);', tn{i}, ir.shocks.count);
end
w.blank();

% ---- model-init segment (ASG refinement on the init problem) --------------
if isfield(ir, 'modelInit')
    addInitSegment(w, ir, pack, m);
    w.blank();
end

w.add('GDSGE_SOL_ASG_INTERP = asg(%s,%d,shock_num);', stateGridCell, numPolicyTotal);
w.add('GDSGE_Metric = 1;');
w.add('GDSGE_MetricVec = [];');
w.add('GDSGE_Iter = 0;');
w.blank();
w.add('if nargin>=1 && isfield(GDSGE_OPTIONS,''WarmUp'')');
w.add('    if isfield(GDSGE_OPTIONS.WarmUp,''asg_interp_struct'')');
w.add('        GDSGE_ASG_INTERP = asg.construct_from_struct(GDSGE_OPTIONS.WarmUp.asg_interp_struct);');
w.add('    end');
w.add('    if isfield(GDSGE_OPTIONS.WarmUp,''Iter'')');
w.add('        GDSGE_Iter = GDSGE_OPTIONS.WarmUp.Iter;');
w.add('    end');
w.add('    if isfield(GDSGE_OPTIONS.WarmUp,''sol_asg_interp_struct'')');
w.add('        GDSGE_SOL_ASG_INTERP = asg.construct_from_struct(GDSGE_OPTIONS.WarmUp.sol_asg_interp_struct);');
w.add('    end');
w.add('end');
w.blank();
% Ping-pong: two persistent buffers per interp (NEW + SPARE), reset() and swapped
% each iteration instead of fresh-allocating a NEW interp and deleting the old
% OLD. The warmup/init OLD is used once then DROPPED, never recycled — it may
% carry a different state range (e.g. widened bounds in a two-stage WarmUp solve)
% that reset() does not touch, which would corrupt value functions built into it.
w.add('GDSGE_ASG_INTERP_NEW = asg(%s,%d,shock_num);', stateGridCell, numel(interpNames));
w.add('GDSGE_ASG_INTERP_SPARE = asg(%s,%d,shock_num);', stateGridCell, numel(interpNames));
w.add('GDSGE_SOL_ASG_INTERP_NEW = asg(%s,%d,shock_num);', stateGridCell, numPolicyTotal);
w.add('GDSGE_SOL_ASG_INTERP_SPARE = asg(%s,%d,shock_num);', stateGridCell, numPolicyTotal);
w.blank();
w.add('GDSGE_RETRY_STATS = gdsge.runtime.retryStatsInit();');
w.add('stopFlag = false;');
w.add('GDSGE_timer = tic;');
w.add('while(~stopFlag)');
w.in();
w.add('GDSGE_Iter = GDSGE_Iter+1;');
w.blank();
w.add('GDSGE_ASG_HANDLE = GDSGE_ASG_INTERP.objectHandle;');
w.add('GDSGE_ASG_INTERP_NEW.reset();');       % NEW carries over from the previous rotation
w.add('GDSGE_SOL_ASG_INTERP_NEW.reset();');
% STORE accumulators: old-template parity — accumulated but never consumed here (no FIX_GRID path emitted).
w.add('GDSGE_ASG_STORE_evalArrayIdx = cell(0);');
w.add('GDSGE_ASG_STORE_evalGridsUnscaled = cell(0);');
w.add('GDSGE_ASG_STORE_output = cell(0);');
w.blank();
w.add('while GDSGE_ASG_INTERP_NEW.get_current_level < AsgMaxLevel');
w.in();
w.add('if GDSGE_ASG_INTERP_NEW.get_current_level<AsgMinLevel');
w.add('    [GDSGE_evalArrayIdx,GDSGE_evalGrids,GDSGE_evalGridsLength,GDSGE_evalGridsUnscaled] = GDSGE_ASG_INTERP_NEW.get_eval_grids(0.0); %%#ok<ASGLU>');
w.add('else');
w.add('    [GDSGE_evalArrayIdx,GDSGE_evalGrids,GDSGE_evalGridsLength,GDSGE_evalGridsUnscaled] = GDSGE_ASG_INTERP_NEW.get_eval_grids(AsgThreshold); %%#ok<ASGLU>');
w.add('end');
w.add('if isempty(GDSGE_evalGrids); break; end');
w.blank();
% depth 8 = 2 codeWriter levels (outer iter while + refinement while), 4 sp/level
addProposeAndSolve(w, main, pack, m, ...
    'GDSGE_SOL_ASG_INTERP_NEW', 'GDSGE_SOL_ASG_INTERP', 8);
w.add('GDSGE_RETRY_STATS = gdsge.runtime.retryStatsAdd(GDSGE_RETRY_STATS, GDSGE_DIAG.minorIters);');
w.blank();
for i = 1:numel(ir.interp)
    w.add('%s = %s;', ir.interp{i}.name, ir.interp{i}.updateExpr);
end
w.add('GDSGE_evalRslts = [%s];', interpSemi);
w.add('GDSGE_SOL_ASG_INTERP_NEW.push_eval_results_at_grids(GDSGE_evalArrayIdx(GDSGE_solved), GDSGE_evalGridsUnscaled(:, GDSGE_solved), GDSGE_SOL(:, GDSGE_solved), GDSGE_SOL_ASG_INTERP_NEW.get_current_level);');
w.add('GDSGE_ASG_INTERP_NEW.push_eval_results_at_valid(GDSGE_evalRslts, GDSGE_solved);');
w.add('GDSGE_ASG_STORE_evalArrayIdx = [GDSGE_ASG_STORE_evalArrayIdx,GDSGE_evalArrayIdx];');
w.add('GDSGE_ASG_STORE_evalGridsUnscaled = [GDSGE_ASG_STORE_evalGridsUnscaled,GDSGE_evalGridsUnscaled];');
if ~isempty(outputs)
    w.add('GDSGE_ASG_STORE_output = [GDSGE_ASG_STORE_output,[%s]];', outputSemi);
end
w.out();
w.add('end');
w.blank();
w.add('[GDSGE_Metric,GDSGE_MetricVec] = asg.compute_inf_metric(GDSGE_ASG_INTERP_NEW, GDSGE_ASG_INTERP);');
% rotate: NEW becomes OLD (this iter's result); swap NEW<->SPARE so the next
% iteration builds into the OTHER buffer. The previous OLD (warmup/init on iter 1,
% a current-range buffer thereafter) is dropped here, never recycled.
w.add('GDSGE_ASG_INTERP = GDSGE_ASG_INTERP_NEW;');
w.add('GDSGE_TMP_PP = GDSGE_ASG_INTERP_NEW; GDSGE_ASG_INTERP_NEW = GDSGE_ASG_INTERP_SPARE; GDSGE_ASG_INTERP_SPARE = GDSGE_TMP_PP;');
w.add('GDSGE_SOL_ASG_INTERP = GDSGE_SOL_ASG_INTERP_NEW;');
w.add('GDSGE_TMP_PP = GDSGE_SOL_ASG_INTERP_NEW; GDSGE_SOL_ASG_INTERP_NEW = GDSGE_SOL_ASG_INTERP_SPARE; GDSGE_SOL_ASG_INTERP_SPARE = GDSGE_TMP_PP;');
w.blank();
w.add('stopFlag = GDSGE_Metric<TolEq || GDSGE_Iter>=MaxIter;');
w.blank();
w.add('GDSGE_RETRY_STATS = gdsge.runtime.retryStatsEndIter(GDSGE_RETRY_STATS, GDSGE_Iter);');
w.add('[GDSGE_PRINTED, GDSGE_RETRY_STATS] = gdsge.runtime.printIterProgress(GDSGE_Iter, GDSGE_Metric, max(GDSGE_F), nnz(~GDSGE_solved), toc(GDSGE_timer), PrintFreq, NoPrint, stopFlag, GDSGE_RETRY_STATS);');
w.add('if GDSGE_PRINTED');
w.add('    GDSGE_timer = tic;');
w.add('end');
w.blank();
w.add('if ( mod(GDSGE_Iter,SaveFreq)==0 || stopFlag == true )');
w.in();
if ~isempty(outputs)
    w.add('if CONSTRUCT_OUTPUT==1');
    w.in();
    w.add('GDSGE_ASG_HANDLE = GDSGE_ASG_INTERP.objectHandle;');
    w.add('GDSGE_ASG_INTERP_OUTPUT = asg(%s,%d,shock_num);', stateGridCell, numOutputTotal);
    w.add('while GDSGE_ASG_INTERP_OUTPUT.get_current_level < AsgOutputMaxLevel');
    w.in();
    w.add('[GDSGE_TEMP_grids, GDSGE_TEMP_surplus, GDSGE_TEMP_levels, GDSGE_TEMP_unscaledGrids] = GDSGE_ASG_INTERP.get_grids_info_at_level(GDSGE_ASG_INTERP_OUTPUT.get_current_level+1); %%#ok<ASGLU>');
    w.add('GDSGE_evalArrayIdx = [];');
    w.add('for GDSGE_I_ARRAY=1:shock_num');
    w.add('    GDSGE_evalArrayIdx = [GDSGE_evalArrayIdx,GDSGE_I_ARRAY*ones(1,size(GDSGE_TEMP_grids{GDSGE_I_ARRAY},2))]; %%#ok<AGROW>');
    w.add('end');
    w.add('GDSGE_evalGrids = cat(2,GDSGE_TEMP_grids{:});');
    w.add('GDSGE_evalGridsUnscaled = cat(2,GDSGE_TEMP_unscaledGrids{:});');
    w.add('if isempty(GDSGE_evalGrids); break; end');
    % depth 16 = 4 levels (iter while + save if + CONSTRUCT_OUTPUT if + output while), 4 sp/level
    addProposeAndSolve(w, main, pack, m, ...
        'GDSGE_SOL_ASG_INTERP', 'GDSGE_SOL_ASG_INTERP', 16);
    w.add('GDSGE_evalRslts = [%s];', outputSemi);
    w.add('GDSGE_ASG_INTERP_OUTPUT.push_eval_results_at_grids(GDSGE_evalArrayIdx(GDSGE_solved), GDSGE_evalGridsUnscaled(:, GDSGE_solved), GDSGE_evalRslts(:, GDSGE_solved), GDSGE_ASG_INTERP_OUTPUT.get_current_level);');
    w.out();
    w.add('end');
    w.add('output_var_index=struct();');
    idx = 1;
    for i = 1:numel(outputs)
        w.add('output_var_index.%s=%d:%d;', outputs{i}, idx, idx + lenOf.(outputs{i}) - 1);
        idx = idx + lenOf.(outputs{i});
    end
    w.add('IterRslt.output_var_index = output_var_index;');
    w.add('IterRslt.asg_output_struct = GDSGE_ASG_INTERP_OUTPUT.convert_to_struct();');
    w.out();
    w.add('end');
end
w.add('IterRslt.Metric = GDSGE_Metric;');
w.add('IterRslt.MetricVec = GDSGE_MetricVec;');
w.add('IterRslt.Iter = GDSGE_Iter;');
w.add('IterRslt.shock_num = shock_num;');
w.add('IterRslt.shock_trans = shock_trans;');
for i = 1:numel(ir.shocks.names)
    w.add('IterRslt.var_shock.%s = %s;', ir.shocks.names{i}, ir.shocks.names{i});
end
for i = 1:numel(ir.states.names)
    w.add('IterRslt.var_state.%s = %s;', ir.states.names{i}, ir.states.names{i});
end
for i = 1:numel(ir.params)
    w.add('IterRslt.params.%s = %s;', ir.params{i}.name, ir.params{i}.name);
end
w.add('IterRslt.params.GDSGE_EMPTY = GDSGE_EMPTY;');
w.add('IterRslt.asg_interp_struct = GDSGE_ASG_INTERP.convert_to_struct();');
w.add('IterRslt.sol_asg_interp_struct = GDSGE_SOL_ASG_INTERP.convert_to_struct();');
for i = 1:numel(ir.variables.others)
    nm = ir.variables.others{i};
    w.add('IterRslt.var_others.%s = %s;', nm, nm);
end
w.add('IterRslt.var_others.GDSGE_EMPTY = GDSGE_EMPTY;');
w.add('if ~NoSave');
w.add('    if IterSaveAll');
w.add('        save([''IterRslt_%s_'' num2str(GDSGE_Iter) ''.mat'']);', m);
w.add('    else');
w.add('        save([''IterRslt_%s_'' num2str(GDSGE_Iter) ''.mat''],''IterRslt'');', m);
w.add('    end');
w.add('end');
w.out();
w.add('end');
w.out();
w.add('end');
w.blank();
w.add('IterFlag = 0;');
w.add('end');
w.blank();
w.add('function [GDSGE_LB,GDSGE_UB] = GDSGE_ADAPT_TIGHT(GDSGE_SOL,GDSGE_LB,GDSGE_UB)');
if isempty(bounds.adaptiveTight)
    w.add('%% no adaptive bounds in this model');
else
    w.addRaw(bounds.adaptiveTight);
end
w.add('end');
txt = w.str();
end

% =========================================================================
function addProposeAndSolve(w, main, pack, m, newSolName, oldSolName, depth)
% One batch at the proposed grids (old asg_propose_grids_and_solve_template):
% bounds, pre-warm from the PREVIOUS-iteration sol interp, allocate, pack,
% solve through gdsge.runtime.solveProblemsAsg, unpack rows + GDSGE_solved.
ind = repmat(' ', 1, depth);
w.add('GDSGE_NPROB = size(GDSGE_evalGrids,2);');
w.add('GDSGE_SIZE = [1,GDSGE_NPROB];');
w.addRaw(gdsge.codegen.mat.indentBy(main.bounds.init, ind));
w.add('GDSGE_SOL0 = (GDSGE_LB + GDSGE_UB)/2;');
w.add('GDSGE_SOL = GDSGE_SOL0;');
w.add('if %s.get_current_level>=0', oldSolName);
w.add('    GDSGE_SOL0 = %s.eval_vec(GDSGE_evalArrayIdx,GDSGE_evalGrids);', oldSolName);
w.add('    GDSGE_SOL = GDSGE_SOL0;');
w.add('    if UseAdaptiveBound==1');
w.add('        [GDSGE_LB,GDSGE_UB] = GDSGE_ADAPT_TIGHT(GDSGE_SOL,GDSGE_LB,GDSGE_UB);');
w.add('    end');
w.add('end');
w.add('GDSGE_EQVAL = 1e20*ones(%d,GDSGE_NPROB);', main.maxDim);
w.add('GDSGE_F = 1e20*ones(1,GDSGE_NPROB);');
w.add('GDSGE_AUX = zeros(%d,GDSGE_NPROB);', main.nAux);
w.add('GDSGE_DATA = zeros(%d,GDSGE_NPROB);', pack.maxData);
w.add('%s', pack.asgPack);
for cfgLine = gdsge.codegen.mat.emitCfgCommon(); w.add('%s', cfgLine{1}); end
w.add('GDSGE_CFG.useBroydenNow = 0;');
w.add('GDSGE_CFG.taskName = MEX_TASK_INF_HORIZON;');
w.add('GDSGE_CFG.asgHandle = GDSGE_ASG_HANDLE;');
w.add('GDSGE_CFG.solInterpNew = %s;', newSolName);
w.add('GDSGE_CFG.solInterpOld = %s;', oldSolName);
w.add('GDSGE_CFG.evalArrayIdx = GDSGE_evalArrayIdx;');
w.add('GDSGE_CFG.evalGrids = GDSGE_evalGrids;');
w.add('GDSGE_CFG.useAdaptiveBound = UseAdaptiveBound;');
w.add('GDSGE_CFG.adaptTight = @GDSGE_ADAPT_TIGHT;');
w.add('GDSGE_CFG.maxMinorIter = MaxMinorIter;');
w.add('GDSGE_CFG.verboseRetry = ~NoPrint;');
w.add('GDSGE_CFG.resolvePrintFreq = ResolvePrintFreq;');
w.add('GDSGE_CFG.majorIter = GDSGE_Iter;');
w.add('if UseAdaptiveBoundInSol==1');
w.add('    GDSGE_CFG.adaptInSol = @GDSGE_ADAPT_TIGHT;');
w.add('else');
w.add('    GDSGE_CFG.adaptInSol = [];');
w.add('end');
w.add('[GDSGE_SOL,GDSGE_F,GDSGE_AUX,GDSGE_EQVAL,GDSGE_OPT_INFO,GDSGE_DIAG] = gdsge.runtime.solveProblemsAsg(@mex_%s, GDSGE_SOL, GDSGE_LB, GDSGE_UB, GDSGE_DATA, GDSGE_F, GDSGE_AUX, GDSGE_EQVAL, GDSGE_CFG); %%#ok<ASGLU>', m);
w.add('GDSGE_solved = GDSGE_DIAG.solved;');
w.addRaw(gdsge.codegen.mat.indentBy(main.unpack, ind));
w.addRaw(gdsge.codegen.mat.indentBy(main.unpackAux, ind));
end

% =========================================================================
function addInitSegment(w, ir, pack, m)
% Old iter_init_asg_template.m parity: ASG refinement on the init problem
% seeds the var_interp interpolant. Gated ONLY by SkipModelInit. The init
% cascade has no warm/restore steps (solInterpNew/Old = []) and no adaptive
% tighten. asgHandle is unused by task_init (its INTERP_GET_CODE is empty).
iv = gdsge.codegen.initView(ir);
boundsInit = gdsge.codegen.mat.emitBounds(iv, 'asg');
unpkInit = gdsge.codegen.mat.emitSolUnpack(iv);
nAuxInit = 0;
for i = 1:numel(iv.variables.aux); nAuxInit = max(nAuxInit, iv.variables.aux{i}.slot(2)); end
stateList = strjoin(ir.states.names, ',');
stateGridCell = ['{' stateList '}'];
interpNames = ir.variables.interp;
interpSemi = strjoin(interpNames, ';');
w.add('%%%% Model-init solve (ASG; old semantics: gated by SkipModelInit only)');
w.add('if ~SkipModelInit');
w.in();
w.add('GDSGE_ASG_INTERP = asg(%s,%d,shock_num);', stateGridCell, numel(interpNames));
w.add('while GDSGE_ASG_INTERP.get_current_level < AsgMaxLevel');
w.in();
w.add('if GDSGE_ASG_INTERP.get_current_level<AsgMinLevel');
w.add('    [GDSGE_evalArrayIdx,GDSGE_evalGrids,GDSGE_evalGridsLength] = GDSGE_ASG_INTERP.get_eval_grids(0.0); %%#ok<ASGLU>');
w.add('else');
w.add('    [GDSGE_evalArrayIdx,GDSGE_evalGrids,GDSGE_evalGridsLength] = GDSGE_ASG_INTERP.get_eval_grids(AsgThreshold); %%#ok<ASGLU>');
w.add('end');
w.add('if isempty(GDSGE_evalGrids); break; end');
w.add('GDSGE_NPROB = size(GDSGE_evalGrids,2);');
w.add('GDSGE_SIZE = [1,GDSGE_NPROB];');
w.addRaw(gdsge.codegen.mat.indentBy(boundsInit.init, '        '));
w.add('GDSGE_SOL = (GDSGE_LB + GDSGE_UB)/2;');
w.add('GDSGE_EQVAL = 1e20*ones(%d,GDSGE_NPROB);', boundsInit.maxDim);
w.add('GDSGE_F = 1e20*ones(1,GDSGE_NPROB);');
w.add('GDSGE_AUX = zeros(%d,GDSGE_NPROB);', max(nAuxInit, 1));
w.add('GDSGE_DATA = zeros(%d,GDSGE_NPROB);', pack.maxData);
w.add('%s', pack.asgPack);
for cfgLine = gdsge.codegen.mat.emitCfgCommon(); w.add('%s', cfgLine{1}); end
w.add('GDSGE_CFG.useBroydenNow = 0;');
w.add('GDSGE_CFG.taskName = MEX_TASK_INIT;');
w.add('GDSGE_CFG.asgHandle = [];');
w.add('GDSGE_CFG.solInterpNew = [];');
w.add('GDSGE_CFG.solInterpOld = [];');
w.add('GDSGE_CFG.evalArrayIdx = GDSGE_evalArrayIdx;');
w.add('GDSGE_CFG.evalGrids = GDSGE_evalGrids;');
w.add('GDSGE_CFG.useAdaptiveBound = 0;');
w.add('GDSGE_CFG.adaptTight = [];');
w.add('GDSGE_CFG.adaptInSol = [];');
w.add('GDSGE_CFG.maxMinorIter = MaxMinorIter;');
w.add('GDSGE_CFG.verboseRetry = ~NoPrint;');
w.add('GDSGE_CFG.resolvePrintFreq = ResolvePrintFreq;');
w.add('GDSGE_CFG.majorIter = 0;');   % ASG model_init runs before GDSGE_Iter exists
w.add('[GDSGE_SOL,GDSGE_F,GDSGE_AUX,GDSGE_EQVAL,GDSGE_OPT_INFO,GDSGE_DIAG] = gdsge.runtime.solveProblemsAsg(@mex_%s, GDSGE_SOL, GDSGE_LB, GDSGE_UB, GDSGE_DATA, GDSGE_F, GDSGE_AUX, GDSGE_EQVAL, GDSGE_CFG); %%#ok<ASGLU>', m);
w.add('GDSGE_solved = GDSGE_DIAG.solved;');
w.addRaw(gdsge.codegen.mat.indentBy(unpkInit.unpack, '        '));
w.addRaw(gdsge.codegen.mat.indentBy(unpkInit.unpackAux, '        '));
for i = 1:numel(ir.interp)
    w.add('%s = %s;', ir.interp{i}.name, ir.interp{i}.initialExpr);
end
w.add('GDSGE_evalRslts = [%s];', interpSemi);
w.add('GDSGE_ASG_INTERP.push_eval_results_at_valid(GDSGE_evalRslts, GDSGE_solved);');
w.out();
w.add('end');
w.out();
w.add('end');
end
