function txt = emitSimulateAsg(ir)
% EMITSIMULATEASG  simulate_<model>.m for interpMethod='asg' (SIMU_RESOLVE;
%   old simulate_resolve_asg_template.m parity). Per period: warm-start the
%   solver from the solution interpolant (sol_asg_interp_struct), re-solve
%   through the MEX with the converged var-interp ASG (asg_interp_struct)
%   evaluated inside the equations via GDSGE_ASG_HANDLE. The retry cascade is
%   first-call + randomized restarts — exactly gdsge.runtime.solveProblems
%   with useNearestNeighbor=false. Old parity notes: bounds come from the
%   gmod inbound code only (no GDSGE_PROB widening — the ASG IterRslt has no
%   GDSGE_PROB); both corpus models have setup-constant bounds.
bounds = gdsge.codegen.mat.emitBounds(ir);
pack   = gdsge.codegen.mat.emitDataPack(ir);
unpk   = gdsge.codegen.mat.emitSolUnpack(ir);
simu   = gdsge.codegen.mat.emitResultSimu(ir);
m      = ir.modelName;
nAux   = 0;
for i = 1:numel(ir.variables.aux); nAux = max(nAux, ir.variables.aux{i}.slot(2)); end
stateNameCell = ['{''' strjoin(ir.states.names, ''',''') '''}'];
stateList = strjoin(ir.states.names, ','); % comma-joined for the reportUnconverged grid-cell argument
simuStateRows = strjoin(cellfun(@(s) ['SimuRslt.' s '(:,GDSGE_t)'''], ...
    ir.states.names, 'UniformOutput', false), ';');

w = gdsge.codegen.codeWriter();
w.add('%% Generated by gdsge.codegen.generateMatlab — do not edit.');
w.add('function SimuRslt = simulate_%s(IterRslt,GDSGE_OPTIONS)', m);
w.add('gdsge.runtime.ensurePath();');
w.blank();
w.addRaw(gdsge.codegen.mat.emitSetup(ir, 'simulate'));
w.blank();
w.add('GEN_SHOCK_START_PERIOD = 1;');
w.blank();
w.add('%% ---- pull the solved model from IterRslt (explicit assignments)');
tn = fieldnames(ir.shocks.transitions);
for i = 1:numel(tn)
    w.add('%s = IterRslt.shock_trans;', tn{i});
end
for i = 1:numel(ir.params)
    w.add('%s = IterRslt.params.%s;', ir.params{i}.name, ir.params{i}.name);
end
for i = 1:numel(ir.shocks.names)
    w.add('%s = IterRslt.var_shock.%s;', ir.shocks.names{i}, ir.shocks.names{i});
end
for i = 1:numel(ir.states.names)
    w.add('%s = IterRslt.var_state.%s;', ir.states.names{i}, ir.states.names{i});
end
w.add('shock_num = IterRslt.shock_num;');
w.blank();
w.add('GDSGE_OPTIONS_VALID = %s;', gdsge.codegen.mat.optionsWhitelist(ir, {'init','GEN_SHOCK_START_PERIOD'}));
w.add('if nargin < 2; GDSGE_OPTIONS = struct(); end');
w.add('gdsge.runtime.unpackOptions(GDSGE_OPTIONS, GDSGE_OPTIONS_VALID);');
w.blank();
w.add('%% ---- reconstruct the converged interpolants');
w.add('GDSGE_ASG_INTERP = asg.construct_from_struct(IterRslt.asg_interp_struct);');
w.add('GDSGE_ASG_HANDLE = GDSGE_ASG_INTERP.objectHandle;');
w.add('GDSGE_SOL_ASG_INTERP = asg.construct_from_struct(IterRslt.sol_asg_interp_struct);');
w.blank();
w.add('GDSGE_NPROB = num_samples;');
w.add('SimuRslt.shock = ones(num_samples,num_periods+1);');
w.addRaw(simu.prealloc);
w.blank();
w.addRaw(simu.init);
w.blank();
w.add('if nargin>1 && isfield(GDSGE_OPTIONS,''init'')');
w.addRaw(indent4(simu.initOverwrite));
w.add('end');
w.add('if any(SimuRslt.shock(:,1)>shock_num)');
w.add('    error(''initial shock exceeds shock_num'');');
w.add('end');
w.blank();
w.addRaw(bounds.init);
w.blank();
w.add('GDSGE_EQVAL = 1e20*ones(%d,GDSGE_NPROB);', bounds.maxDim);
w.add('GDSGE_F = 1e20*ones(1,GDSGE_NPROB);');
w.add('GDSGE_SOL = zeros(%d,GDSGE_NPROB);', bounds.maxDim);
w.add('GDSGE_AUX = zeros(%d,GDSGE_NPROB);', max(nAux, 1));
w.blank();
w.add('SimuRslt.shock(:,GEN_SHOCK_START_PERIOD:end) = gen_discrete_markov_rn(shock_trans,num_samples,length(GEN_SHOCK_START_PERIOD:num_periods+1),...');
w.add('    SimuRslt.shock(:,GEN_SHOCK_START_PERIOD));');
w.blank();
% Note: simuData0 and shock generation are order-independent (simuData0 holds only constants); emitSimulate.m orders them the other way.
w.add('%s', pack.simuData0);
w.add('GDSGE_SHOCK_VAR_INDEX_BASE = ([0:num_samples-1]'')*shock_num;');
w.add('GDSGE_timer = tic;');
w.add('for GDSGE_t=1:num_periods');
w.in();
w.add('shock = SimuRslt.shock(:,GDSGE_t);');
for i = 1:numel(ir.states.names)
    w.add('%s=SimuRslt.%s(:,GDSGE_t);', ir.states.names{i}, ir.states.names{i});
end
w.blank();
% parity: simulate_resolve_asg_template.m line 78
w.add('%% solution-interp warm start');
w.add('GDSGE_SOL = GDSGE_SOL_ASG_INTERP.eval_vec(SimuRslt.shock(:,GDSGE_t)'',[%s]);', simuStateRows);
w.blank();
w.add('if UseAdaptiveBoundInSol==1');
w.add('    GDSGE_LB_OLD = GDSGE_LB; GDSGE_UB_OLD = GDSGE_UB;');
w.add('    [GDSGE_LB,GDSGE_UB] = GDSGE_ADAPT_TIGHT(GDSGE_SOL,GDSGE_LB,GDSGE_UB);');
w.add('    GDSGE_SOL_hitting_lower_bound = abs(GDSGE_SOL - GDSGE_LB_OLD) < 1e-8;');
w.add('    GDSGE_SOL_hitting_upper_bound = abs(GDSGE_SOL - GDSGE_UB_OLD) < 1e-8;');
w.add('    GDSGE_LB(~GDSGE_SOL_hitting_lower_bound) = GDSGE_LB_OLD(~GDSGE_SOL_hitting_lower_bound);');
w.add('    GDSGE_UB(~GDSGE_SOL_hitting_upper_bound) = GDSGE_UB_OLD(~GDSGE_SOL_hitting_upper_bound);');
w.add('end');
w.blank();
w.add('%s', pack.simuPack);
w.blank();
for cfgLine = gdsge.codegen.mat.emitCfgCommon(); w.add('%s', cfgLine{1}); end
w.add('GDSGE_CFG.useBroydenNow = 0;');
w.add('GDSGE_CFG.taskName = MEX_TASK_INF_HORIZON;');
w.add('GDSGE_CFG.splineVec = [];');
w.add('GDSGE_CFG.ppNames = {}; GDSGE_CFG.ppCell = {};');
w.add('GDSGE_CFG.asgHandle = GDSGE_ASG_HANDLE;');
w.add('GDSGE_CFG.maxMinorIter = MaxMinorIter;');
w.add('GDSGE_CFG.probSize = [1 GDSGE_NPROB];');
w.add('GDSGE_CFG.useNearestNeighbor = false;');
w.add('GDSGE_CFG.verboseRetry = false;');
w.add('if UseAdaptiveBoundInSol==1');
w.add('    GDSGE_CFG.adaptInSol = @GDSGE_ADAPT_TIGHT;');
w.add('else');
w.add('    GDSGE_CFG.adaptInSol = [];');
w.add('end');
w.add('[GDSGE_SOL,GDSGE_F,GDSGE_AUX,GDSGE_EQVAL,GDSGE_OPT_INFO,GDSGE_DIAG] = gdsge.runtime.solveProblems(@mex_%s, GDSGE_SOL, GDSGE_LB, GDSGE_UB, GDSGE_DATA, GDSGE_F, GDSGE_AUX, GDSGE_EQVAL, GDSGE_CFG); %%#ok<ASGLU>', m);
w.add('if any(GDSGE_DIAG.needResolved)');
w.add('    warning(''gdsge:runtime:unconverged'', ''period %%d: %%s'', GDSGE_t, gdsge.runtime.reportUnconverged(GDSGE_DIAG.needResolved, GDSGE_F, [1 GDSGE_NPROB], %s, {%s}, 5));', ...
    stateNameCell, stateList);
w.add('end');
w.blank();
w.addRaw(indent4(unpk.unpack));
w.addRaw(indent4(unpk.unpackAux));
w.blank();
w.add('GDSGE_SHOCK_VAR_LINEAR_INDEX = SimuRslt.shock(:,GDSGE_t+1) + GDSGE_SHOCK_VAR_INDEX_BASE;');
w.addRaw(indent4(simu.assign));
w.blank();
w.add('if mod(GDSGE_t,SimuPrintFreq)==0');
w.add('    fprintf(''Periods: %%d\\n'', GDSGE_t);');
w.add('    SimuRsltNames = fieldnames(SimuRslt);');
w.add('    for GDSGE_field = 1:length(SimuRsltNames)');
w.add('        fprintf(''%%8s'', SimuRsltNames{GDSGE_field});');
w.add('    end');
w.add('    fprintf(''\\n'');');
w.add('    for GDSGE_field = 1:length(SimuRsltNames)');
w.add('        fprintf(''%%8.4g'', SimuRslt.(SimuRsltNames{GDSGE_field})(1,GDSGE_t));');
w.add('    end');
w.add('    fprintf(''\\n'');');
w.add('    fprintf(''elapsed:%%.1fs\\n'', toc(GDSGE_timer));');
w.add('    GDSGE_timer = tic;');
w.add('end');
w.add('if mod(GDSGE_t,SimuSaveFreq)==0');
w.add('    save([''SimuRslt_%s_'' num2str(GDSGE_t) ''.mat''], ''SimuRslt'');', m);
w.add('end');
w.out();
w.add('end');
w.add('end');
w.blank();
w.add('function [GDSGE_LB,GDSGE_UB] = GDSGE_ADAPT_TIGHT(GDSGE_SOL,GDSGE_LB,GDSGE_UB)');
if isempty(bounds.adaptiveTight)
    w.add('%% no adaptive bounds in this model');
else
    w.addRaw(bounds.adaptiveTight);
end
w.add('end');
txt = w.str();
end

function s = indent4(s)
s = gdsge.codegen.mat.indentBy(s, '    ');
end
