function txt = emitSimulateInterp(ir)
% EMITSIMULATEINTERP  simulate_<model>.m, SIMU_INTERP variant: no per-period
%   re-solve. var_output values come from the output interpolant evaluated at
%   the realized (shock, state) points each period; var_simu fields and state
%   transitions are then assigned exactly as in the resolve variant. Spline
%   (MEX-expressible): the whole loop runs in simulate_<model>_mex over the
%   stacked uniform-order IterRslt.output_interp; otherwise a per-period
%   interp_eval_mex fallback loop. ASG (interpMethod='asg'):
%   asg.construct_from_struct(IterRslt.asg_output_struct) via eval_vec. Old
%   parity: code_template/simulate_interp_template.m + gdsge_parser.m:1684-1737.
simu = gdsge.codegen.mat.emitResultSimu(ir);
m = ir.modelName;
isAsg = strcmp(ir.options.interpMethod, 'asg');
% Spline + MEX-expressible simulate block -> whole loop runs in
% simulate_<model>_mex; otherwise the per-period interp_eval_mex fallback loop.
useMex = ~isAsg && gdsge.codegen.cxx.isSimuMexExpressible(ir);
simuStateRows = strjoin(cellfun(@(s) ['SimuRslt.' s '(:,GDSGE_t)'''], ...
    ir.states.names, 'UniformOutput', false), ';');

w = gdsge.codegen.codeWriter();
w.add('%% Generated by gdsge.codegen.generateMatlab — do not edit.');
w.add('function SimuRslt = simulate_%s(IterRslt,GDSGE_OPTIONS)', m);
w.add('gdsge.runtime.ensurePath();');
w.blank();
w.addRaw(gdsge.codegen.mat.emitSetup(ir, 'simulate'));
w.blank();
w.add('GEN_SHOCK_START_PERIOD = 1;');
w.blank();
w.add('%% ---- pull the solved model from IterRslt');
for i = 1:numel(ir.states.names)
    w.add('%s = IterRslt.var_state.%s;', ir.states.names{i}, ir.states.names{i});
end
w.add('shock_trans = IterRslt.shock_trans;');
w.add('shock_num = IterRslt.shock_num;');
w.add('output_var_index = IterRslt.output_var_index;');
if isAsg
    w.add('GDSGE_ASG_OUTPUT_INTERP = asg.construct_from_struct(IterRslt.asg_output_struct);');
else
    w.add('GDSGE_PP = IterRslt.output_interp;');
    w.add('GDSGE_NCOMP = IterRslt.output_interp.GDSGE_NCOMP;');
end
w.blank();
base = {'SimuPrintFreq','SimuSaveFreq','num_samples','num_periods', ...
    'NumThreads','EnforceSimuStateInbound','GEN_SHOCK_START_PERIOD','init'};
wl = [base, ir.states.names];
w.add('GDSGE_OPTIONS_VALID = {%s};', ['''' strjoin(wl, ''',''') '''']);
w.add('if nargin < 2; GDSGE_OPTIONS = struct(); end');
w.add('gdsge.runtime.unpackOptions(GDSGE_OPTIONS, GDSGE_OPTIONS_VALID);');
w.blank();
w.add('SimuRslt.shock = ones(num_samples,num_periods+1);');
w.addRaw(simu.prealloc);
w.blank();
w.addRaw(simu.init);
w.blank();
w.add('if nargin>1 && isfield(GDSGE_OPTIONS,''init'')');
w.addRaw(indent4(simu.initOverwrite));
w.add('end');
w.add('if any(SimuRslt.shock(:,1)>shock_num)');
w.add('    error(''initial shock exceeds shock_num'');');
w.add('end');
w.blank();
w.add('SimuRslt.shock(:,GEN_SHOCK_START_PERIOD:end) = gen_discrete_markov_rn(shock_trans,num_samples,length(GEN_SHOCK_START_PERIOD:num_periods+1),...');
w.add('    SimuRslt.shock(:,GEN_SHOCK_START_PERIOD));');
w.blank();
w.add('GDSGE_timer = tic;');
if useMex
    % Whole loop in C++. State fields need num_periods+1 columns (the MEX writes
    % the (:,t+1) transition at t=num_periods and cannot grow the array; MATLAB
    % auto-grows in the fallback). Chunk by SimuSaveFreq so mid-run saves remain.
    for i = 1:numel(ir.states.names)
        w.add('SimuRslt.%s(:,num_periods+1) = 0;', ir.states.names{i});
    end
    w.add('GDSGE_T0 = 1;');
    w.add('while GDSGE_T0 <= num_periods');
    w.add('    GDSGE_T1 = min(GDSGE_T0 + SimuSaveFreq - 1, num_periods);');
    w.add('    simulate_%s_mex(int32(NumThreads), GDSGE_PP, int32(GDSGE_NCOMP), ...', m);
    w.add('        SimuRslt.shock, SimuRslt, int32([GDSGE_T0 GDSGE_T1]), int32(num_periods), ...');
    w.add('        int32(EnforceSimuStateInbound), int32(SimuPrintFreq));');
    w.add('    if mod(GDSGE_T1,SimuSaveFreq)==0');
    w.add('        save([''SimuRslt_%s_'' num2str(GDSGE_T1) ''.mat''], ''SimuRslt'');', m);
    w.add('    end');
    w.add('    fprintf(''elapsed:%%.1fs\\n'', toc(GDSGE_timer)); GDSGE_timer = tic;');
    w.add('    GDSGE_T0 = GDSGE_T1 + 1;');
    w.add('end');
else
    w.add('GDSGE_SHOCK_VAR_INDEX_BASE = ([0:num_samples-1]'')*shock_num;');
    w.add('for GDSGE_t=1:num_periods');
    w.in();
    w.add('if EnforceSimuStateInbound==1');
    for i = 1:numel(ir.states.names)
        s = ir.states.names{i};
        w.add('    SimuRslt.%s(:,GDSGE_t)=max(min(IterRslt.var_state.%s),SimuRslt.%s(:,GDSGE_t));', s, s, s);
        w.add('    SimuRslt.%s(:,GDSGE_t)=min(max(IterRslt.var_state.%s),SimuRslt.%s(:,GDSGE_t));', s, s, s);
    end
    w.add('end');
    w.blank();
    if isAsg
        w.add('GDSGE_INTERP_RESULTS = GDSGE_ASG_OUTPUT_INTERP.eval_vec(SimuRslt.shock(:,GDSGE_t)'',[%s]);', simuStateRows);
    else
        % Stacked uniform-order eval: site = states only; per-sample vector index
        % selects the realized shock's component block (s-1)*nComp + (0:nComp-1).
        w.add('GDSGE_IDX = int32((SimuRslt.shock(:,GDSGE_t)''-1)*GDSGE_NCOMP + (0:GDSGE_NCOMP-1)'');');
        w.add('GDSGE_INTERP_RESULTS = interp_eval_mex(int32(NumThreads), GDSGE_PP, [%s], GDSGE_IDX);', simuStateRows);
    end
    for i = 1:numel(ir.variables.output)
        n = ir.variables.output{i};
        w.add('%s=GDSGE_INTERP_RESULTS(output_var_index.%s,:);', n, n);
    end
    w.blank();
    w.add('GDSGE_SHOCK_VAR_LINEAR_INDEX = SimuRslt.shock(:,GDSGE_t+1) + GDSGE_SHOCK_VAR_INDEX_BASE;');
    w.addRaw(indent4(simu.assign));
    w.blank();
    w.add('if mod(GDSGE_t,SimuPrintFreq)==0');
    w.add('    fprintf(''Periods: %%d\\n'', GDSGE_t);');
    w.add('    fprintf(''elapsed:%%.1fs\\n'', toc(GDSGE_timer));');
    w.add('    GDSGE_timer = tic;');
    w.add('end');
    w.add('if mod(GDSGE_t,SimuSaveFreq)==0');
    w.add('    save([''SimuRslt_%s_'' num2str(GDSGE_t) ''.mat''], ''SimuRslt'');', m);
    w.add('end');
    w.out();
    w.add('end');
end
w.add('end');
txt = w.str();
end

function s = indent4(s)
s = gdsge.codegen.mat.indentBy(s, '    ');
end
