function lines = emitCfgCommon()
% EMITCFGCOMMON  Return the shared GDSGE_CFG spine lines as a cell array.
%   These 5 w.add() calls are identical in emitIter, emitSimulate, and
%   emitIterInit.  Variant fields (useBroydenNow, taskName, splineVec,
%   ppNames, ppCell, probSize, useNearestNeighbor, verboseRetry,
%   adaptInSol, maxMinorIter) stay at each call site.
lines = { ...
    'GDSGE_CFG = struct();', ...
    'GDSGE_CFG.tolSol = TolSol; GDSGE_CFG.tolFun = TolFun;', ...
    'GDSGE_CFG.solMaxIter = SolMaxIter; GDSGE_CFG.numThreads = NumThreads;', ...
    'GDSGE_CFG.debugEvalOnly = GDSGE_DEBUG_EVAL_ONLY;', ...
    'GDSGE_CFG.useBroyden = UseBroyden; GDSGE_CFG.finiteDiffDelta = FiniteDiffDelta;', ...
};
end
