function txt = emitIter(ir)
% EMITITER  Assemble the complete iter_<model>.m from IR sections.
%   Thin generated file: model-specific code only; algorithmic blocks live in
%   gdsge.runtime.*. Parity reference: scratch/old_generated/iter_HL1996.m.
bounds = gdsge.codegen.mat.emitBounds(ir);
pack   = gdsge.codegen.mat.emitDataPack(ir);
unpk   = gdsge.codegen.mat.emitSolUnpack(ir);
m      = ir.modelName;
% GDSGE_DATA holds the constant parameter block + the fixed solve grid; the
% data that changes between iterations (the policy/value functions) reaches the
% MEX via GDSGE_SPLINE_VEC / GDSGE_PP_*, not GDSGE_DATA. So the pack is
% loop-invariant and can be built ONCE — unless a pre_iter hook could mutate a
% param, in which case keep the per-iteration rebuild.
hoistData = ~(isfield(ir.hooks, 'preIter') && ~isempty(ir.hooks.preIter));
nAux   = 0;
for i = 1:numel(ir.variables.aux); nAux = max(nAux, ir.variables.aux{i}.slot(2)); end
interpNames = ir.variables.interp;                     % decl order
interpList  = strjoin(interpNames, ',');               % 'ps_future,pb_future,...'
stateList   = strjoin(ir.states.names, ',');           % 'w1'
stateNameCell = ['{''' strjoin(ir.states.names, ''',''') '''}'];   % {'w1'}
stateGridCell = ['{' stateList '}'];                                % {w1}
solComp     = gdsge.codegen.mat.solComponentNames(ir);
solNamesLit = ['{''' strjoin(solComp, ''',''') '''}'];              % {'c',...,'w1n(8)'}
tensorRows  = ['[GDSGE_TENSOR_shockIdx(:)'';' ...
    strjoin(cellfun(@(s) ['GDSGE_TENSOR_' s '(:)'''], ir.states.names, ...
    'UniformOutput', false), ';') ']'];

w = gdsge.codegen.codeWriter();
w.add('%% Generated by gdsge.codegen.generateMatlab — do not edit.');
w.add('function [IterRslt,IterFlag] = iter_%s(GDSGE_OPTIONS)', m);
w.add('gdsge.runtime.ensurePath();');
w.blank();
w.addRaw(gdsge.codegen.mat.emitSetup(ir, 'iter'));
w.blank();

% ---- options unpacking (whitelist = frozen surface + model + setup names) -
w.add('GDSGE_OPTIONS_VALID = %s;', gdsge.codegen.mat.optionsWhitelist(ir, {}));
w.add('if nargin < 1; GDSGE_OPTIONS = struct(); end');
w.add('gdsge.runtime.unpackOptions(GDSGE_OPTIONS, GDSGE_OPTIONS_VALID);');
w.blank();

% ---- declaration asserts (parity with old lines 111-116) ------------------
w.add('assert(exist(''shock_num'',''var'')==1);');
for i = 1:numel(ir.shocks.names)
    w.add('assert(length(%s)==%d);', ir.shocks.names{i}, ir.shocks.count);
end
tn = fieldnames(ir.shocks.transitions);
for i = 1:numel(tn)
    w.add('assert(size(%s,1)==%d);', tn{i}, ir.shocks.count);
    w.add('assert(size(%s,2)==%d);', tn{i}, ir.shocks.count);
end
w.blank();

% ---- state-space tensors ---------------------------------------------------
w.add('%%%% State-space tensors');
w.add('[GDSGE_TENSOR_shockIdx,%s]=ndgrid(1:shock_num,%s);', ...
    strjoin(cellfun(@(s) ['GDSGE_TENSOR_' s], ir.states.names, 'UniformOutput', false), ','), ...
    stateList);
for i = 1:numel(ir.shocks.names)
    w.add('GDSGE_TENSOR_%s=ndgrid(%s,%s);', ir.shocks.names{i}, ir.shocks.names{i}, stateList);
end
% ---- var_tensor construction (broadcast over the state×shock grid) --------
if ~isempty(ir.variables.tensor)
    w.add('%%%% Tensor variables');
    rwNames = [ir.states.names, ir.shocks.names];
    rwReps  = cellfun(@(n) ['GDSGE_TENSOR_' n], rwNames, 'UniformOutput', false);
    for i = 1:numel(ir.variables.tensor)
        t = ir.variables.tensor{i};
        rhs = gdsge.codegen.mat.rewriteNames(t.expr, rwNames, rwReps);
        w.add('GDSGE_TENSOR_%s = %s;', t.name, rhs);
        rwNames{end+1} = t.name;                       %#ok<AGROW>
        rwReps{end+1}  = ['GDSGE_TENSOR_' t.name];     %#ok<AGROW>
    end
end
w.add('GDSGE_NPROB=numel(GDSGE_TENSOR_shockIdx);');
w.add('GDSGE_SIZE = size(GDSGE_TENSOR_shockIdx);');
w.add('GDSGE_SIZE_STATE = num2cell(GDSGE_SIZE(2:end));');
w.blank();

initSeg = gdsge.codegen.mat.emitIterInit(ir);
if ~isempty(initSeg)
    w.addRaw(initSeg);
    w.blank();
end

% ---- bounds + solution space ----------------------------------------------
w.add('%%%% Bounds');
w.addRaw(bounds.init);
w.blank();
w.add('%%%% Solution space');
w.add('GDSGE_EQVAL = 1e20*ones(%d,GDSGE_NPROB);', bounds.maxDim);
w.add('GDSGE_F = 1e20*ones(1,GDSGE_NPROB);');
w.add('GDSGE_SOL = zeros(%d,GDSGE_NPROB);', bounds.maxDim);
w.add('if UseMexRandomize');
w.add('    GDSGE_SOL(:) = (GDSGE_LB + GDSGE_UB) / 2;   %% deterministic midpoint; restarts drawn in the MEX');
w.add('else');
w.add('    GDSGE_X0 = rand(size(GDSGE_SOL)) .* (GDSGE_UB-GDSGE_LB) + GDSGE_LB;');
w.add('    GDSGE_SOL(:) = GDSGE_X0;');
w.add('end');
w.add('GDSGE_AUX = zeros(%d,GDSGE_NPROB);', max(nAux, 1));
w.add('GDSGE_DATA = zeros(%d,GDSGE_NPROB);', pack.maxData);
w.add('NeedResolved = false(1,GDSGE_NPROB);');
w.blank();

% ---- interp initialization (skipped under interp WarmUp; parity line 172) --
w.add('%%%% Interp initialization');
w.add('if ~( nargin>=1 && isfield(GDSGE_OPTIONS,''WarmUp'') && isfield(GDSGE_OPTIONS.WarmUp,''var_interp'') )');
w.in();
w.addRaw(indent4(gdsge.codegen.mat.emitInterpInitial(ir)));
w.add('[GDSGE_PP_CELL, GDSGE_SPLINE_VEC] = gdsge.runtime.constructSplines({%s}, %s, GDSGE_SIZE_STATE, INTERP_ORDER, EXTRAP_ORDER, NumThreads);', ...
    interpList, stateGridCell);
for i = 1:numel(interpNames)
    w.add('GDSGE_PP_%s = GDSGE_PP_CELL{%d};', interpNames{i}, i);
end
w.out();
w.add('end');
w.blank();

w.add('GDSGE_Metric = 1;');
w.add('GDSGE_Iter = 0;');
w.add('IS_WARMUP_LOOP = 0;');
w.blank();

% ---- WarmUp ----------------------------------------------------------------
w.add('if nargin>=1 && isfield(GDSGE_OPTIONS,''WarmUp'')');
w.in();
w.add('GDSGE_WARMUP = GDSGE_OPTIONS.WarmUp;');
w.add('if isfield(GDSGE_WARMUP,''var_interp'')');
w.in();
for i = 1:numel(interpNames)
    n = interpNames{i};
    w.add('if isfield(GDSGE_WARMUP.var_interp,''%s''); %s = GDSGE_WARMUP.var_interp.%s; end', n, n, n);
end
w.add('if isfield(GDSGE_WARMUP,''GDSGE_PROB'')');
w.add('    GDSGE_SIZE_STATE_WU = num2cell(GDSGE_WARMUP.GDSGE_PROB.GDSGE_SIZE(2:end));');
w.add('else');
w.add('    GDSGE_SIZE_STATE_WU = GDSGE_SIZE_STATE;');
w.add('end');
w.add('if isfield(GDSGE_WARMUP,''var_state'')');
w.add('    GDSGE_BREAKS_WU = {%s};', strjoin(cellfun(@(s) ...
    ['GDSGE_WARMUP.var_state.' s], ir.states.names, 'UniformOutput', false), ','));
w.add('else');
w.add('    GDSGE_BREAKS_WU = %s;', stateGridCell);
w.add('end');
w.add('[GDSGE_PP_CELL, GDSGE_SPLINE_VEC] = gdsge.runtime.constructSplines({%s}, GDSGE_BREAKS_WU, GDSGE_SIZE_STATE_WU, INTERP_ORDER, EXTRAP_ORDER, NumThreads);', interpList);
for i = 1:numel(interpNames)
    w.add('GDSGE_PP_%s = GDSGE_PP_CELL{%d};', interpNames{i}, i);
end
w.add('IS_WARMUP_LOOP = 1;');
w.out();
w.add('end');
w.add('if isfield(GDSGE_WARMUP,''Iter''); GDSGE_Iter = GDSGE_WARMUP.Iter; end');
w.add('GDSGE_WARMSPEC = struct();');
w.add('GDSGE_WARMSPEC.shockNum = shock_num;');
w.add('GDSGE_WARMSPEC.stateNames = %s;', stateNameCell);
w.add('GDSGE_WARMSPEC.evalPoints = %s;', tensorRows);
w.add('GDSGE_WARMSPEC.adaptiveSlots = %s;', mat2str(bounds.adaptiveSlots));
w.add('GDSGE_WARMSPEC.reuseSol = REUSE_WARMUP_SOL;');
w.add('GDSGE_WARMSPEC.interpSol = INTERP_WARMUP_SOL;');
w.add('GDSGE_WARMSPEC.numThreads = NumThreads;');
w.add('[GDSGE_SOL, GDSGE_LB, GDSGE_UB] = gdsge.runtime.applyWarmUp(GDSGE_WARMUP, GDSGE_SOL, GDSGE_LB, GDSGE_UB, GDSGE_WARMSPEC);');
w.out();
w.add('end');
w.blank();

% ---- GDSGE_DATA: build once when loop-invariant (no pre_iter) ---------------
if hoistData
    w.add('%%%% GDSGE_DATA holds constant params + the fixed solve grid; build it once.');
    w.add('%s', pack.iterPack);
    w.blank();
end

% ---- GDSGE_CFG: built once; only splineVec/ppCell/useBroydenNow change per iter
% (the rest is set from options and is loop-invariant). solveProblems treats it
% as read-only, so the struct persists across iterations.
w.add('%%%% Solver config: built once; only splineVec/ppCell/useBroydenNow change per iter.');
for cfgLine = gdsge.codegen.mat.emitCfgCommon(); w.add('%s', cfgLine{1}); end
w.add('GDSGE_CFG.taskName = MEX_TASK_INF_HORIZON;');
ppNamesLit = ['{''' strjoin(cellfun(@(n) ['GDSGE_PP_' n], interpNames, ...
    'UniformOutput', false), ''',''') '''}'];
w.add('GDSGE_CFG.ppNames = %s;', ppNamesLit);
w.add('GDSGE_CFG.maxMinorIter = MaxMinorIter;');
w.add('GDSGE_CFG.probSize = GDSGE_SIZE;');
w.add('GDSGE_CFG.useNearestNeighbor = true;');
w.add('GDSGE_CFG.useMexResolve = UseMexResolve;');
w.add('GDSGE_CFG.useMexRandomize = UseMexRandomize;');
w.add('GDSGE_CFG.randomizeBatch = MexRandomizeBatch;');
w.add('GDSGE_CFG.randomSeed = MexRandomSeed;');
w.add('GDSGE_CFG.verboseRetry = ~NoPrint;');
w.add('GDSGE_CFG.resolvePrintFreq = ResolvePrintFreq;');
w.add('GDSGE_CFG.solNames = %s;', solNamesLit);
w.add('GDSGE_CFG.stateNames = %s;', stateNameCell);
w.add('GDSGE_CFG.stateGrids = %s;', stateGridCell);
w.add('GDSGE_CFG.diagnoseAt = DiagnoseMinorIter;');
w.add('GDSGE_CFG.errorOnNonconvergence = true;');
w.add('if UseAdaptiveBoundInSol==1');
w.add('    GDSGE_CFG.adaptInSol = @GDSGE_ADAPT_TIGHT;');
w.add('else');
w.add('    GDSGE_CFG.adaptInSol = [];');
w.add('end');
w.blank();

% ---- main loop --------------------------------------------------------------
w.add('GDSGE_RETRY_STATS = gdsge.runtime.retryStatsInit();');
w.add('stopFlag = false;');
w.add('GDSGE_timer = tic;');
w.add('while(~stopFlag)');
w.in();
w.add('GDSGE_Iter = GDSGE_Iter+1;');
w.blank();
if ~hoistData
    w.add('%s', pack.iterPack);
    w.blank();
end
w.add('GDSGE_CFG.useBroydenNow = double(GDSGE_Iter>1)*GDSGE_USE_BROYDEN;');
w.add('GDSGE_CFG.randomizeSalt = GDSGE_Iter;');
w.add('GDSGE_CFG.majorIter = GDSGE_Iter;');
w.add('GDSGE_CFG.splineVec = GDSGE_SPLINE_VEC;');
w.add('GDSGE_CFG.ppCell = GDSGE_PP_CELL;');
w.add('[GDSGE_SOL,GDSGE_F,GDSGE_AUX,GDSGE_EQVAL,GDSGE_OPT_INFO,GDSGE_DIAG] = gdsge.runtime.solveProblems(@mex_%s, GDSGE_SOL, GDSGE_LB, GDSGE_UB, GDSGE_DATA, GDSGE_F, GDSGE_AUX, GDSGE_EQVAL, GDSGE_CFG); %%#ok<ASGLU>', m);
w.add('NeedResolved = GDSGE_DIAG.needResolved;');
w.add('GDSGE_RETRY_STATS = gdsge.runtime.retryStatsAdd(GDSGE_RETRY_STATS, GDSGE_DIAG.minorIters);');
w.blank();
w.addRaw(indent4(unpk.unpack));
w.addRaw(indent4(unpk.unpackAux));
w.addRaw(indent4(unpk.reshapeShock));
w.blank();
for i = 1:numel(ir.interp)
    it = ir.interp{i};
    w.add('GDSGE_NEW_%s = %s;', it.name, it.updateExpr);
end
newList = strjoin(cellfun(@(n) ['GDSGE_NEW_' n], interpNames, 'UniformOutput', false), ',');
w.add('GDSGE_Metric = gdsge.runtime.computeMetric({%s},{%s});', newList, interpList);
w.add('GDSGE_Metric0 = GDSGE_Metric;');
w.add('if IS_WARMUP_LOOP==1');
w.add('    IS_WARMUP_LOOP = 0;');
w.add('end');
for i = 1:numel(interpNames)
    w.add('%s=GDSGE_NEW_%s;', interpNames{i}, interpNames{i});
end
w.blank();
w.addRaw(indent4(bounds.adaptiveWiden));
w.blank();
w.add('stopFlag = (isempty(GDSGE_Metric) || GDSGE_Metric<TolEq) || GDSGE_Iter>=MaxIter;');
w.blank();
w.add('[GDSGE_PP_CELL, GDSGE_SPLINE_VEC] = gdsge.runtime.constructSplines({%s}, %s, GDSGE_SIZE_STATE, INTERP_ORDER, EXTRAP_ORDER, NumThreads);', ...
    interpList, stateGridCell);
for i = 1:numel(interpNames)
    w.add('GDSGE_PP_%s = GDSGE_PP_CELL{%d};', interpNames{i}, i);
end
w.blank();
w.add('GDSGE_RETRY_STATS = gdsge.runtime.retryStatsEndIter(GDSGE_RETRY_STATS, GDSGE_Iter);');
w.add('[GDSGE_PRINTED, GDSGE_RETRY_STATS] = gdsge.runtime.printIterProgress(GDSGE_Iter, GDSGE_Metric, max(GDSGE_F), nnz(NeedResolved), toc(GDSGE_timer), PrintFreq, NoPrint, stopFlag, GDSGE_RETRY_STATS);');
w.add('if GDSGE_PRINTED');
w.add('    GDSGE_timer = tic;');
w.add('end');
w.blank();
w.add('if ( (mod(GDSGE_Iter,SaveFreq)==0 || stopFlag == true) )');
w.in();
w.addRaw(indent8(unpk.reshapeSize));
w.addRaw(indent8(gdsge.codegen.mat.emitResultIter(ir)));
w.add('if ~NoSave');
w.add('    if IterSaveAll');
w.add('        save([''IterRslt_%s_'' num2str(GDSGE_Iter) ''.mat'']);', m);
w.add('    else');
w.add('        save([''IterRslt_%s_'' num2str(GDSGE_Iter) ''.mat''],''IterRslt'');', m);
w.add('    end');
w.add('end');
w.out();
w.add('end');
w.out();
w.add('end');
w.blank();
w.add('IterFlag = 0;');
w.add('end');
w.blank();

% ---- model-specific adaptive-tighten subfunction ---------------------------
w.add('function [GDSGE_LB,GDSGE_UB] = GDSGE_ADAPT_TIGHT(GDSGE_SOL,GDSGE_LB,GDSGE_UB)');
if isempty(bounds.adaptiveTight)
    w.add('%% no adaptive bounds in this model');
else
    w.addRaw(bounds.adaptiveTight);
end
w.add('end');
txt = w.str();
end

function s = indent4(s)
s = gdsge.codegen.mat.indentBy(s, '    ');
end
function s = indent8(s)
s = gdsge.codegen.mat.indentBy(s, '        ');
end
