function lit = optionsWhitelist(ir, extra)
% OPTIONSWHITELIST  The GDSGE_OPTIONS_VALID cell literal shared by all
%   generated entry points: frozen option surface + model names + gmod
%   setup-assigned names (old semantics: GDSGE_OPTIONS may override anything
%   the declaration-region code defined, e.g. Bianchi's bMin/bMax).
base = {'TolEq','TolSol','TolFun','PrintFreq','ResolvePrintFreq','NoPrint','SaveFreq','NoSave', ...
    'SimuPrintFreq','SimuSaveFreq','MaxIter','MaxMinorIter','num_samples', ...
    'num_periods','SolMaxIter','UseBroyden','FiniteDiffDelta','GDSGE_USE_BROYDEN', ...
    'GDSGE_DEBUG_EVAL_ONLY','INTERP_ORDER','EXTRAP_ORDER','OutputInterpOrder', ...
    'IterSaveAll','SkipModelInit','UseAdaptiveBound','UseAdaptiveBoundInSol', ...
    'EnforceSimuStateInbound','REUSE_WARMUP_SOL','INTERP_WARMUP_SOL', ...
    'CONSTRUCT_OUTPUT','NumThreads','WarmUp','UseMexResolve','DiagnoseMinorIter', ...
    'UseMexRandomize','MexRandomizeBatch','MexRandomSeed'};
modelNames = {};
for i = 1:numel(ir.params); modelNames{end+1} = ir.params{i}.name; end %#ok<AGROW>
modelNames = [modelNames, ir.shocks.names, fieldnames(ir.shocks.transitions)', ir.states.names];
setupNames = {};
if isfield(ir, 'setupNames'); setupNames = reshape(ir.setupNames, 1, []); end
wl = unique([base, modelNames, setupNames, reshape(extra, 1, [])], 'stable');
lit = ['{''' strjoin(wl, ''',''') '''}'];
end
