function txt = emitTask(ir, taskName)
% EMITTASK  One task function from the task template. taskName selects which
%   (task_inf_horizon for the main model, task_init for ir-as-initView).
if nargin < 2; taskName = 'task_inf_horizon'; end
import gdsge.codegen.cxx.fillTemplate
import gdsge.codegen.cxx.readTemplate
[modelCode, callFMinCode, numEq] = gdsge.codegen.cxx.emitModel(ir);
interp = gdsge.codegen.cxx.emitInterp(ir);
numAux = sum(cellfun(@(a) a.length, ir.variables.aux));
txt = fillTemplate(readTemplate('task.tpl.cpp'), { ...
    'PRE_MODEL_CODE',        ir.hooks.preModel; ...
    'START_LOOP_CODE',       ''; ...
    'FINISH_LOOP_CODE',      ''; ...
    'MODEL_CODE',            modelCode; ...
    'CALL_FMIN_CODE',        callFMinCode; ...
    'POP_CODE',              gdsge.codegen.cxx.emitPop(ir); ...
    'INTERP_GET_CODE',       interp.getCode; ...
    'INTERP_GET_THREAD_CODE', interp.threadCode; ...
    'NUM_EQUATIONS',         num2str(numEq); ...
    'NUM_AUX',               num2str(numAux); ...
    'TASK_NAME',             taskName});
end
